import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import { mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { EdgeBlockedError } from '@chrischall/mcp-utils';
import { createTestHarness, parseToolResult } from '@chrischall/mcp-utils/test';
import { exchangeAuthorizationCode } from '../src/auth.js';
import { FreshbooksClient } from '../src/client.js';
import { registerAuthTools } from '../src/tools/auth.js';
import { consentRedirect } from './consent-helpers.js';
import { registerHealthcheckTools } from '../src/tools/healthcheck.js';

/**
 * A CDN/WAF block is not a FreshBooks answer (chrischall/mcp-host#1015).
 *
 * An edge refusal page is HTML, so the client's "non-JSON response" branch
 * threw a fixed message with no body and no status — the shared healthcheck
 * could only call it `unknown`. These run the REAL client (fetch stubbed) on
 * the probe and on the token refresh the probe triggers.
 */

const CLOUDFRONT_BLOCK =
  '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">' +
  '<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">' +
  '<TITLE>ERROR: The request could not be satisfied</TITLE></HEAD><BODY>' +
  '<H1>403 ERROR</H1><H2>The request could not be satisfied.</H2><HR noshade size="1px">' +
  "Request blocked. We can't connect to the server for this app or website at this time." +
  '<BR clear="all"><HR noshade size="1px"><PRE>Generated by cloudfront (CloudFront)\n' +
  'Request ID: AbCdEfGhIjKlMnOpQrStUvWxYz0123456789==</PRE><ADDRESS></ADDRESS></BODY></HTML>';

const blocked = () =>
  new Response(CLOUDFRONT_BLOCK, {
    status: 403,
    headers: { 'content-type': 'text/html', 'x-cache': 'Error from cloudfront' },
  });

const tokenOk = () =>
  new Response(
    JSON.stringify({
      access_token: 'at',
      refresh_token: 'rt2',
      created_at: Math.floor(Date.now() / 1000),
      expires_in: 3600,
    }),
    { status: 200 },
  );

interface Result {
  ok: boolean;
  error?: { kind: string; message: string };
  hint: string;
}

describe('a CDN/WAF block reads as edge_blocked, not an unknown failure', () => {
  const saved = { ...process.env };
  let dir: string;

  beforeEach(() => {
    dir = mkdtempSync(join(tmpdir(), 'fb-edge-'));
    process.env.FRESHBOOKS_CLIENT_ID = 'cid';
    process.env.FRESHBOOKS_CLIENT_SECRET = 'csecret';
    process.env.FRESHBOOKS_REFRESH_TOKEN = 'rt';
  });

  afterEach(() => {
    process.env = { ...saved };
    rmSync(dir, { recursive: true, force: true });
  });

  async function healthcheck(route: (url: string) => Response): Promise<Result> {
    const fetchImpl = (async (url: string) => route(String(url))) as unknown as typeof fetch;
    const client = new FreshbooksClient({ fetchImpl, storePath: join(dir, 'tokens.json') });
    const h = await createTestHarness((server) => registerHealthcheckTools(server, client));
    const res = await h.client.callTool({ name: 'freshbooks_healthcheck', arguments: {} });
    await h.close?.();
    return parseToolResult<Result>(res as never);
  }

  it('on the /users/me probe', async () => {
    const r = await healthcheck((url) => (url.includes('/auth/oauth/token') ? tokenOk() : blocked()));
    expect(r.ok).toBe(false);
    expect(r.error?.kind).toBe('edge_blocked');
  });

  it('on the token refresh the probe triggers', async () => {
    const r = await healthcheck(() => blocked());
    expect(r.ok).toBe(false);
    expect(r.error?.kind).toBe('edge_blocked');
  });
});

describe('a CDN/WAF block on the authorization-code exchange reads as edge_blocked', () => {
  const saved = { ...process.env };
  let dir: string;

  beforeEach(() => {
    dir = mkdtempSync(join(tmpdir(), 'fb-edge-code-'));
    for (const name of ['FRESHBOOKS_REFRESH_TOKEN', 'FRESHBOOKS_REDIRECT_URI', 'MCP_DATA_DIR']) {
      delete process.env[name];
    }
    process.env.FRESHBOOKS_CLIENT_ID = 'cid';
    process.env.FRESHBOOKS_CLIENT_SECRET = 'csecret';
    process.env.FRESHBOOKS_TOKEN_STORE = join(dir, 'session.json');
  });

  afterEach(() => {
    vi.unstubAllGlobals();
    process.env = { ...saved };
    rmSync(dir, { recursive: true, force: true });
  });

  const config = { clientId: 'cid', clientSecret: 'csecret', redirectUri: 'https://localhost', refreshToken: '' };

  it('throws EdgeBlockedError rather than a generic non-JSON error', async () => {
    const fetchImpl = (async () => blocked()) as unknown as typeof fetch;
    const err = await exchangeAuthorizationCode(config, 'thecode', fetchImpl).catch((e: unknown) => e);
    expect(err).toBeInstanceOf(EdgeBlockedError);
    expect((err as Error).message).toMatch(/POST \/auth\/oauth\/token/);
    expect((err as Error).message).not.toMatch(/non-JSON/);
  });

  it('through freshbooks_auth_exchange, without disturbing the saved credentials', async () => {
    // A first, successful local authorization leaves a saved credential.
    vi.stubGlobal('fetch', vi.fn(async () => tokenOk()));
    const h = await createTestHarness((server) => registerAuthTools(server));
    try {
      const first = await h.callTool('freshbooks_auth_exchange', { code: await consentRedirect(h, 'code-1') });
      expect(first.isError).toBeFalsy();
      const before = readFileSync(process.env.FRESHBOOKS_TOKEN_STORE as string, 'utf8');
      expect(before).toContain('rt2');

      // A re-authorization that the edge refuses must name the block and leave
      // the saved credential exactly as it was.
      vi.stubGlobal('fetch', vi.fn(async () => blocked()));
      const res = await h.callTool('freshbooks_auth_exchange', { code: await consentRedirect(h, 'code-2') });
      expect(res.isError).toBe(true);
      const text = JSON.stringify(res);
      expect(text).toMatch(/CDN\/WAF \(CloudFront\)/);
      expect(text).not.toMatch(/non-JSON/);
      expect(readFileSync(process.env.FRESHBOOKS_TOKEN_STORE as string, 'utf8')).toBe(before);
    } finally {
      await h.close();
    }
  });
});
