import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createTestHarness, parseToolResult } from '@chrischall/mcp-utils/test';
import { FreshbooksClient } from '../src/client.js';
import { registerHealthcheckTools } from '../src/tools/healthcheck.js';

/**
 * A CDN/WAF block is not a FreshBooks answer (chrischall/mcp-host#1015).
 *
 * An edge refusal page is HTML, so the client's "non-JSON response" branch
 * threw a fixed message with no body and no status — the shared healthcheck
 * could only call it `unknown`. These run the REAL client (fetch stubbed) on
 * the probe and on the token refresh the probe triggers.
 */

const CLOUDFRONT_BLOCK =
  '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">' +
  '<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">' +
  '<TITLE>ERROR: The request could not be satisfied</TITLE></HEAD><BODY>' +
  '<H1>403 ERROR</H1><H2>The request could not be satisfied.</H2><HR noshade size="1px">' +
  "Request blocked. We can't connect to the server for this app or website at this time." +
  '<BR clear="all"><HR noshade size="1px"><PRE>Generated by cloudfront (CloudFront)\n' +
  'Request ID: AbCdEfGhIjKlMnOpQrStUvWxYz0123456789==</PRE><ADDRESS></ADDRESS></BODY></HTML>';

const blocked = () =>
  new Response(CLOUDFRONT_BLOCK, {
    status: 403,
    headers: { 'content-type': 'text/html', 'x-cache': 'Error from cloudfront' },
  });

const tokenOk = () =>
  new Response(
    JSON.stringify({
      access_token: 'at',
      refresh_token: 'rt2',
      created_at: Math.floor(Date.now() / 1000),
      expires_in: 3600,
    }),
    { status: 200 },
  );

interface Result {
  ok: boolean;
  error?: { kind: string; message: string };
  hint: string;
}

describe('a CDN/WAF block reads as edge_blocked, not an unknown failure', () => {
  const saved = { ...process.env };
  let dir: string;

  beforeEach(() => {
    dir = mkdtempSync(join(tmpdir(), 'fb-edge-'));
    process.env.FRESHBOOKS_CLIENT_ID = 'cid';
    process.env.FRESHBOOKS_CLIENT_SECRET = 'csecret';
    process.env.FRESHBOOKS_REFRESH_TOKEN = 'rt';
  });

  afterEach(() => {
    process.env = { ...saved };
    rmSync(dir, { recursive: true, force: true });
  });

  async function healthcheck(route: (url: string) => Response): Promise<Result> {
    const fetchImpl = (async (url: string) => route(String(url))) as unknown as typeof fetch;
    const client = new FreshbooksClient({ fetchImpl, storePath: join(dir, 'tokens.json') });
    const h = await createTestHarness((server) => registerHealthcheckTools(server, client));
    const res = await h.client.callTool({ name: 'freshbooks_healthcheck', arguments: {} });
    await h.close?.();
    return parseToolResult<Result>(res as never);
  }

  it('on the /users/me probe', async () => {
    const r = await healthcheck((url) => (url.includes('/auth/oauth/token') ? tokenOk() : blocked()));
    expect(r.ok).toBe(false);
    expect(r.error?.kind).toBe('edge_blocked');
  });

  it('on the token refresh the probe triggers', async () => {
    const r = await healthcheck(() => blocked());
    expect(r.ok).toBe(false);
    expect(r.error?.kind).toBe('edge_blocked');
  });
});
